# docker-compose-common.yml
#
# This file is used to define the common settings for all the containers.
# It as to be extend for each new service needing it.
#
# author [Lars Dethlefsen] - lars.dethlefsen@gmail.com
# version 0.1
# date 2025-01-27

# Copyright (c) 2025 - DTU. All rights reserved.

services:
  common:
    build:
      context: ../../..
      network: host
      dockerfile: t5.3-rebar-detection/docker/main_pkg/Dockerfile

    image: registry.gitlab.com/certh-iti-robotics-lab/robetarme/robetarme/ros-noetic/t5.3-irr-rebars-segmentation:development
    container_name: ros_noetic_t5.3_irr_rebars_segmentation_development

    stdin_open: true
    tty: true
    network_mode: host
    ipc: host

    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"

    environment:
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}

      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../../catkin_ws/src:/home/robetarme_user/catkin_ws/src:rw
      - ../../shared:/home/robetarme_user/shared:rw
