steps:
  - uses: ros-tooling/setup-ros@v0.7
    with:
      required-ros-distributions: noetic
  - uses: ros-tooling/action-ros-ci@v0.3
    with:
      package-name: rebarsegmenation
      target-ros1-distro: noetic
