steps:
  - uses: ros-tooling/setup-ros@v0.7
    with:
      required-ros-distributions: noetic
  - uses: ros-tooling/action-ros-ci@v0.3
    with:
      package-name: my_package
      target-ros2-distro: jazzy
